# Generated by Django 4.2.20 on 2025-04-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="media_file",
            field=models.FileField(upload_to=""),
        ),
    ]
