# Generated by Django 4.2.20 on 2025-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_content_media_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="media_file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
