# Generated by Django 4.2.20 on 2025-05-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_content_media_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color_palette", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="eventpackage",
            name="moods",
            field=models.ManyToManyField(
                related_name="event_packages", to="events.mood"
            ),
        ),
    ]
