# Generated by Django 4.2.20 on 2025-05-07 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_mood_eventpackage_moods"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealingIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("recommended_duration", models.IntegerField(default=3)),
                ("emoji", models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="HealingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("activity_type", models.CharField(max_length=50)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.healingintent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventpackage",
            name="healing_intents",
            field=models.ManyToManyField(
                related_name="event_packages", to="events.healingintent"
            ),
        ),
    ]
