# Generated by Django 4.2.20 on 2025-07-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0006_remove_booking_consultation_datetime_booking_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="gender",
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="guides/"),
                ),
                (
                    "expertise",
                    models.CharField(
                        help_text="e.g. Yoga, Mindfulness, Adventure Travel",
                        max_length=100,
                    ),
                ),
                (
                    "packages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which experiences this guide leads",
                        related_name="guides",
                        to="events.eventpackage",
                    ),
                ),
            ],
        ),
    ]
