# Generated by Django 4.2.20 on 2025-10-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_booking_address_alter_booking_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
