# Generated by Django 4.2.20 on 2025-11-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_content_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
    ]
