# Generated by Django 4.2.20 on 2025-11-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_content_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mood",
            name="color_palette",
        ),
        migrations.AddField(
            model_name="mood",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="eventpackage",
            name="moods",
            field=models.ManyToManyField(blank=True, to="events.mood"),
        ),
        migrations.AlterField(
            model_name="mood",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
