# Generated by Django 4.2.20 on 2025-11-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_content_slug"),
        ("events", "0010_remove_mood_color_palette_mood_icon_and_more"),
    ]

    operations = []
