# Generated by Django 4.2.20 on 2025-11-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_merge_20251111_1307"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="media_file",
            new_name="src",
        ),
        migrations.AddField(
            model_name="mood",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="moods/"),
        ),
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
    ]
